#!/bin/bash
set -o allexport
source .env
cp proxy.conf $PROXY_CONF_DIR
set +o allexport
docker volume create --name=log
docker-compose pull --no-parallel
docker network create --subnet=172.18.0.0/16 --gateway=172.18.0.1 ngix-network
